"""Shared feature-schema constants for the paper-reproduction experiments."""

CRYPTO_ASSETS = ("BTC", "ETH", "LTC", "BNB")
PORTFOLIO_ASSETS = (*CRYPTO_ASSETS, "USDT")
TECHNICAL_INDICATORS = ("SMA20", "EMA20", "MACD", "RSI14")

PRICE_DIM = len(PORTFOLIO_ASSETS)
INDICATOR_DIM = len(PORTFOLIO_ASSETS) * len(TECHNICAL_INDICATORS)
TOTAL_FEATURE_DIM = PRICE_DIM + INDICATOR_DIM

